import gleam/string

pub const build_dir = "./build/dev/javascript/_giolt_build"

pub const file_name = "index.mjs"

pub const path = "./build/dev/javascript/_giolt_build/index.mjs"

const template = "// Generated by the Giolt SDK. Do not edit.
import * as conversation from \"../conversation/conversation.mjs\";
import * as app from \"{entry}\";

export default {
  async fetch(request, _env, _ctx) {
    const req = conversation.to_gleam_request(request);
    const response = await app.handler(req);

    return conversation.to_js_response(response);
  },
};
"

pub fn render(specifier: String) -> String {
  string.replace(template, "{entry}", specifier)
}
