import gleam/string

pub const build_dir = "./build/dev/javascript/_giolt_build"

pub const path = "./build/dev/javascript/_giolt_build/index.mjs"

const template = "// Generated by the Giolt SDK. Do not edit.
import * as conversation from \"../conversation/conversation.mjs\";
import * as app from \"{entry}\";

export default {
  async fetch(request, _env, _ctx) {
    if (typeof app.handler !== \"function\") {
      return new Response(
        \"[Giolt SDK] {entry} does not export a `handler` function.\",
        { status: 500 },
      );
    }

    const req = conversation.to_gleam_request(request);
    const response = await app.handler(req);

    return conversation.to_js_response(response);
  },
};
"

pub fn render(specifier: String) -> String {
  string.replace(template, "{entry}", specifier)
}
