//// The worker entry Giolt actually deploys.
////
//// The user's entry module exports a `handler` taking a `conversation`
//// request; the platform speaks `fetch`. This module renders the small bridge
//// between the two, which is what esbuild is pointed at.

import gleam/string

/// Directory the rendered shim is written to, beside the compiled packages so
/// that `../{project}/{module}.mjs` resolves.
pub const build_dir = "./build/dev/javascript/_giolt_build"

/// File name of the rendered shim.
pub const file_name = "index.mjs"

/// Full path of the rendered shim.
pub const path = "./build/dev/javascript/_giolt_build/index.mjs"

const template = "// Generated by the Giolt SDK. Do not edit.
import * as conversation from \"../conversation/conversation.mjs\";
import * as app from \"{entry}\";

export default {
  async fetch(request, _env, _ctx) {
    const req = conversation.to_gleam_request(request);
    const response = await app.handler(req);

    return conversation.to_js_response(response);
  },
};
"

/// Render the shim for an entry module.
///
/// `specifier` is the import path of the compiled entry, as produced by
/// `giolt_sdk/internal/entry.shim_specifier`.
pub fn render(specifier: String) -> String {
  string.replace(template, "{entry}", specifier)
}
